# Generated by Django 6.0.6 on 2026-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("inventory__gte", 0)),
                name="product_inventory_non_negative",
            ),
        ),
    ]
