# Generated by Django 6.0.6 on 2026-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_product_inventory_non_negative"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["product", "status"], name="store_comme_product_9e48a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="store_order_status_428b25_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-datetime_created"], name="store_order_datetim_06a0c9_idx"
            ),
        ),
    ]
