[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_tests.py tests.py
addopts = --reuse-db --nomigrations --strict-markers
markers =
    api: API endpoint tests
    models: model tests
    serializers: serializer tests
